### ISSUE TITLE
Can you add a property to the pileup component to fill in the title?

### ISSUE THREAD

**Issue by tonydisera** [anderspitman/vue-pileup#2]
<img width="437" alt="screen shot 2018-10-25 at 4 28 21 pm" src="https://user-images.githubusercontent.com/8420103/47534015-16ca5e80-d873-11e8-8fe5-b2fba0098d97.png">

**Comment by anderspitman** [comment]
@tonydisera what would you expect to see in here exactly? I believe the `igv-content-header` div normally just contains an ideogram for the chromosome.

**Comment by tonydisera** [comment]
I see.  I guess it might be better to just have a title in the dialog, which would be in gene.iobio.  No problem!

**Comment by anderspitman** [comment]
Yeah that might be helpful, especially if it says whether it's the proband/mother/father/etc

**Comment by tonydisera** [comment]
Actually, I think it would be nice to be able to send in a property to the vue-pileup component to set the igv-header.  Is this possible?  If not, I have to style the .igv-header to display: none to work around so that extra vertical space isn't taken up.

**Comment by anderspitman** [comment]
Yeah you definitely shouldn't have to mess with any of the igv stuff. But I'm not sure vue-pileup should handle the title. What if set display: none for .igv-header and then the consuming application (gene in this case) can decide whether to add a title or not?

**Comment by tonydisera** [comment]
Sure thing.  That is how I am handling it now.  This probably gives us more flexibility.  I'll close this issue.

**Comment by anderspitman** [comment]
@tonydisera sorry I typo'd. I meant to say how about I set display: none within vue-pileup so that you don't have to worry about it externally?

**Comment by anderspitman** [comment]
Fixed in #8
