### ISSUE TITLE
Would you be able to add an amino-acid track for the reference?

### ISSUE THREAD

**Issue by tonydisera** [anderspitman/vue-pileup#5]

**Comment by anderspitman** [comment]
@tonydisera I think this is possible, but I might need to upstream some changes to igv to get it to work. It does take up quite a bit of space to show the sequences, but if we're sure we want it I can look into it more: 
![image](https://user-images.githubusercontent.com/7820200/47685365-e8fb5780-db9b-11e8-85b9-5f59f89631e8.png)

![image](https://user-images.githubusercontent.com/7820200/47685376-f7497380-db9b-11e8-87cc-427cdf85f636.png)

**Comment by anderspitman** [comment]
As you can see I have it basically working (you can actually turn it on now using the built-in menus), but it might be trickier to show it automatically.

**Comment by tonydisera** [comment]
I like that!  It is better that the user can turn it on in the built-in menus.  Thanks!
